### ISSUE TITLE
OnBotTradeOffer() System.TypeLoadException: Could not load type 'EType' from assembly

### ISSUE THREAD

**Issue by GGBot0** [Rudokhvist/ItemDispenser#11]
```
ERROR ASF > OnBotTradeOffer() System.TypeLoadException: Could not load type 'EType' from assembly 'ArchiSteamFarm, Version=6.0.1.24, Culture=neutral, PublicKeyToken=0'.
   at ItemDispenser.ItemDispenser.OnBotTradeOffer(Bot bot, TradeOffer tradeOffer)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at ItemDispenser.ItemDispenser.OnBotTradeOffer(Bot bot, TradeOffer tradeOffer)
   at ArchiSteamFarm.Plugins.PluginsCore.<>c__DisplayClass30_0.<OnBotTradeOffer>b__1(IBotTradeOffer plugin)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll[TResult](IEnumerable`1 tasks)
   at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnBotTradeOffer(Bot bot, TradeOffer tradeOffer)
```

ASF 6.0.1.24 
ItemDispenser 2.0.0.0
linux x64 build

**Comment by Rudokhvist** [comment]
Thank you for report! I'll update is ASAP.

**Comment by Rudokhvist** [comment]
Please check that v.2.0.0.1 fixes this issue for you.

**Comment by GGBot0** [comment]
Hello, it's working as intended now.

Does this plugin have the "PluginsUpdateMode" feature enabled? Unsure how to implement it or if it's even supported.

**Comment by Rudokhvist** [comment]
Thank you for confirmation.

No, none of my plugins have auto-updates implemented yet. I plan to do it at least for some plugins, but don't have much time now to do that.
