### ISSUE TITLE
IBotTradeOffer error in new ASF update

### ISSUE THREAD

**Issue by GGBot0** [Rudokhvist/ItemDispenser#12]
```
2024-08-02 05:09:59|dotnet-1201893|INFO|ASF|InitPlugins() Initializing Plugins...
2024-08-02 05:09:59|dotnet-1201893|ERROR|ASF|InitPlugins() Failed due to error: ItemDispenser, Version=2.0.0.1, Culture=neutral, PublicKeyToken=null
2024-08-02 05:09:59|dotnet-1201893|ERROR|ASF|InitPlugins() System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'ArchiSteamFarm.Plugins.Interfaces.IBotTradeOffer' from assembly 'ArchiSteamFarm, Version=6.0.5.2, Culture=neutral, PublicKeyToken=504f46588cc351a9'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
System.TypeLoadException: Could not load type 'ArchiSteamFarm.Plugins.Interfaces.IBotTradeOffer' from assembly 'ArchiSteamFarm, Version=6.0.5.2, Culture=neutral, PublicKeyToken=504f46588cc351a9'.
2024-08-02 05:10:09|dotnet-1201893|ERROR|ASF|Exit() Exiting with 1 error code!

```

**Comment by Rudokhvist** [comment]
Thank you for the report! I released a new version, give it a try! 
https://github.com/Rudokhvist/ItemDispenser/releases/tag/2.0.1.0
